SPOTeam/Android

SPOTeam_android/.idea/compiler.xml, SPOTeam_android/.idea/gradle.xml, SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/MainActivity.kt, SPOTeam_android/app/src/main/res/layout/activity_main.xml
=> merge conflict 수정/프레드

SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/AndroidManifest.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/ActivityFeeStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MemberStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/res/layout/fragment_activity_fee_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_member_study.xml, SPOTeam_android/app/src/main/res/layout/spinner_dropdown_item.xml, SPOTeam_android/app/src/main/res/layout/spinner_item.xml, SPOTeam_android/app/src/main/res/values/fragment_study_num_spinner_items.xml
스터디 만들기 2차 구현 및 manifest파일 일부 수정
=> 스터디 만들기 2차 구현 및 manifest파일 일부 수정

SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/ActivityFeeStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MemberStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MyStudyRegisterFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt, SPOTeam_android/app/src/main/res/layout/fragment_member_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_my_study_register.xml
=> 이전 프래그먼트 이동 기능 추가

SPOTeam_android/app/src/main/AndroidManifest.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/GlobalApplication.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/RegisterInformation.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt
=> 카카오 로그인 구현 완료

SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LogoutActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt
=> 카카오 로그인,로그아웃, 로컬db 구현 완료

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/ActivityFeeStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyAdapter.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyRegisterApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyRequest.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt, SPOTeam_android/app/src/main/res/layout/fragment_study.xml, SPOTeam_android/app/src/main/res/values/colors.xml
=> 내 스터디 불러오기 api 연동 진행중

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/ActivityFeeStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/DetailStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MyStudyRegisterPreviewFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyAdapter.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyRegisterApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyRequest.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt, SPOTeam_android/app/src/main/res/drawable/fragment_my_study_register_preview_background.xml, SPOTeam_android/app/src/main/res/font/pretendard.xml, SPOTeam_android/app/src/main/res/layout/fragment_detail_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_study.xml, SPOTeam_android/app/src/main/res/layout/item_recycler_view.xml, SPOTeam_android/app/src/main/res/layout/item_recycler_view_plus_toggle.xml, SPOTeam_android/app/src/main/res/values/strings.xml
=> 내 스터디 구현완료 이미지는 구현 진행중

SPOTeam_android/.idea/gradle.xml, SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/MainActivity.kt, SPOTeam_android/app/src/main/res/drawable/detail_study_background.xml, SPOTeam_android/app/src/main/res/layout/activity_main.xml, SPOTeam_android/gradle/wrapper/gradle-wrapper.properties
detail_study_background 및 메인액티비티 수정
=> detail_study_background 및 메인액티비티 수정

SPOTeam_android/app/src/main/java/com/example/spoteam_android/MainActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyAdapter.kt
=> 찜 관련 주석 삭제

SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/HouseFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/MainActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/AllCategoryFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/CategoryStudyContentRVAdapter.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/community/CommunityAPIService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/community/CommunityResponse.kt, SPOTeam_android/app/src/main/res/layout/fragment_house.xml
=> ui 수정 및 연동 완료

SPOTeam_android/.idea/misc.xml, SPOTeam_android/.idea/other.xml, SPOTeam_android/app/src/main/AndroidManifest.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/CellPhoneLoginActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/NormalLoginActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt, SPOTeam_android/app/src/main/res/drawable/edittext_with_text_background.xml, SPOTeam_android/app/src/main/res/drawable/normal_login_edittext_corner_rectangle.xml, SPOTeam_android/app/src/main/res/layout/activity_normal_login.xml, SPOTeam_android/app/src/main/res/values/colors.xml, SPOTeam_android/gradle/libs.versions.toml, SPOTeam_android/gradle/wrapper/gradle-wrapper.properties
[SPOT-49][login] 일반 로그인 기능 및 화면 구현 완료
[SPOT-49]: https://spoteam.atlassian.net/browse/SPOT-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-49][login] 일반 로그인 기능 및 화면 구현 완료

SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginViewModel.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/mypage/MyPageFragment.kt
[SPOT-144][feat] 일반 로그인 일부 구현
[SPOT-144]: https://spoteam.atlassian.net/browse/SPOT-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-144][feat] 일반 로그인 일부 구현

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/RetrofitInstance.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/NormalLoginActivity.kt
[SPOT-144][feat] 아이디 중복 확인 메소드 추가
[SPOT-144]: https://spoteam.atlassian.net/browse/SPOT-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-144][feat] 아이디 중복 확인 메소드 추가

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/RetrofitInstance.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/NormalLoginActivity.kt, SPOTeam_android/app/src/main/res/layout/activity_normal_login.xml
[SPOT-144][feat] 일반 회원가입 화면 구현 완료
[SPOT-144]: https://spoteam.atlassian.net/browse/SPOT-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-144][feat] 일반 회원가입 화면 구현 완료

SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/DetailStudyHomeFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MyStudyCommunityFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MyStudyRegisterPreviewFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyRegisterApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/quiz/QuizViewModel.kt
[SPOT-164][feat] 스터디 부분 UI 1차 수정 진행중
[SPOT-164]: https://spoteam.atlassian.net/browse/SPOT-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-164][feat] 스터디 부분 UI 1차 수정 진행중

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Authenticator.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/RetrofitInstance.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginViewModel.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt
[SPOT-164][feat] 비동기 작업 완료 전 함수 호출 오류 수정 및 토큰 인터셉터 로직 수정
[SPOT-164]: https://spoteam.atlassian.net/browse/SPOT-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-164][feat] 비동기 작업 완료 전 함수 호출 오류 수정 및 토큰 인터셉터 로직 수정

SPOTeam_android/.idea/deploymentTargetSelector.xml, SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/res/layout/item_recycler_view.xml
[SPOT-164][feat] 1차 recyclerView ui 수정 완료
[SPOT-164]: https://spoteam.atlassian.net/browse/SPOT-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-164][feat] 1차 recyclerView ui 수정 완료

SPOTeam_android/.idea/deploymentTargetSelector.xml, SPOTeam_android/.idea/misc.xml, SPOTeam_android/.idea/other.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/HouseFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/bookMark/BookmarkFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyFragment.kt, SPOTeam_android/app/src/main/res/drawable/btn_page_bg.xml, SPOTeam_android/app/src/main/res/layout/fragment_bookmark.xml, SPOTeam_android/app/src/main/res/layout/fragment_study.xml, SPOTeam_android/app/src/main/res/values/themes.xml
[SPOT-178][fix] 내 스터디, 찜 화면 페이징 구현 완료
[SPOT-178]: https://spoteam.atlassian.net/browse/SPOT-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-178][fix] 내 스터디, 찜 화면 페이징 구현 완료

SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/DetailStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/RegisterStudyFragment.kt, SPOTeam_android/app/src/main/res/layout/fragment_register_study.xml
[SPOT-178][fix] 스터디 등록하기 UI 업데이트
[SPOT-178]: https://spoteam.atlassian.net/browse/SPOT-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-178][fix] 스터디 등록하기 UI 업데이트

SPOTeam_android/.idea/misc.xml, SPOTeam_android/.idea/other.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/res/layout/fragment_location_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_online_study.xml, SPOTeam_android/app/src/main/res/values/strings.xml
[SPOT-178][fix] 스터디 정보 수정 UI 변경
[SPOT-178]: https://spoteam.atlassian.net/browse/SPOT-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-178][fix] 스터디 정보 수정 UI 변경

SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/res/layout/fragment_online_study.xml
[SPOT-178][fix] 스터디 등록하기 지역 UI 수정
[SPOT-178]: https://spoteam.atlassian.net/browse/SPOT-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-178][fix] 스터디 등록하기 지역 UI 수정

SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/RetrofitInstance.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginRepository.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginViewModel.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginViewModelFactory.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/TokenManager.kt
[SPOT-222][feat] 로그인 로직 전체 변경 MVVM 패턴 적용
[SPOT-222]: https://spoteam.atlassian.net/browse/SPOT-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-222][feat] 로그인 로직 전체 변경 MVVM 패턴 적용

SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginViewModel.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/TokenManager.kt
[SPOT-222][feat] 자동 로그인 구현
[SPOT-222]: https://spoteam.atlassian.net/browse/SPOT-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-222][feat] 자동 로그인 구현

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/IntroduceStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/util/LocationParser.kt
[SPOT-241][FIX] 스터디 수정부분 수정
[SPOT-241]: https://spoteam.atlassian.net/browse/SPOT-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-241][FIX] 스터디 수정부분 수정

SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/bookMark/BookmarkFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/mypage/ConsiderAttendanceFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/mypage/ParticipatingStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/ActivityFeeStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/IntroduceStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MemberStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/OnlineStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/RegisterStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyRegisterApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/StudyViewModel.kt, SPOTeam_android/app/src/main/res/layout/fragment_activity_fee_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_consider_attendance.xml, SPOTeam_android/app/src/main/res/layout/fragment_introduce_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_member_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_online_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_participating_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_register_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_study.xml
[SPOT-245][FIX] 스터디 수정하기 기능 구현 완료
[SPOT-245]: https://spoteam.atlassian.net/browse/SPOT-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-245][FIX] 스터디 수정하기 기능 구현 완료

SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/CategoryFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/AllCategoryFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/ContestFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/DiscussionFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/FreeStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/JobFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/LanguageFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/LicenseFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/MajorFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/NewsFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/ProjectFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/category/category_tabs/RestFragment.kt, SPOTeam_android/app/src/main/res/layout/fragment_category.xml, SPOTeam_android/app/src/main/res/layout/fragment_category_study_content.xml, SPOTeam_android/app/src/main/res/values/font_styles.xml
[SPOT-245][FIX] 각 페이지 페이징 구현
[SPOT-245]: https://spoteam.atlassian.net/browse/SPOT-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-245][FIX] 각 페이지 페이징 구현

SPOTeam_android/app/src/main/res/layout/fragment_house.xml
[SPOT-247][FIX] 홈 부분 UI수정
[SPOT-247]: https://spoteam.atlassian.net/browse/SPOT-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-247][FIX] 홈 부분 UI수정

SPOTeam_android/app/src/main/java/com/example/spoteam_android/Data.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/RetrofitInstance.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/checklist/CheckListLocationActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/LoginApiService.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/NicNameActivity.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/RegisterInformation.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/login/StartLoginActivity.kt, SPOTeam_android/app/src/main/res/layout/activity_register_information.xml
[SPOT-247][FIX] 닉네임 UI 수정 및 로그인 로직 수정
[SPOT-247]: https://spoteam.atlassian.net/browse/SPOT-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-247][FIX] 닉네임 UI 수정 및 로그인 로직 수정

SPOTeam_android/app/src/main/java/com/example/spoteam_android/checklist/CheckListCategoryActivity.kt
[SPOT-263][FIX] 닉네임 api 수정
[SPOT-263]: https://spoteam.atlassian.net/browse/SPOT-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SPOT-263][FIX] 닉네임 api 수정

SPOTeam_android/.idea/misc.xml, SPOTeam_android/app/src/main/java/com/example/spoteam_android/Authenticator.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/mypage/RegionPreferenceFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/LocationStudyFragment.kt, SPOTeam_android/app/src/main/java/com/example/spoteam_android/ui/study/MemberStudyFragment.kt, SPOTeam_android/app/src/main/res/layout/activity_check_list_category.xml, SPOTeam_android/app/src/main/res/layout/activity_check_list_study_purpose.xml, SPOTeam_android/app/src/main/res/layout/dialog_logout.xml, SPOTeam_android/app/src/main/res/layout/dialog_purpose_upload_complete.xml, SPOTeam_android/app/src/main/res/layout/fragment_activity_fee_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_introduce_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_location_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_member_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_my_page_location.xml, SPOTeam_android/app/src/main/res/layout/fragment_online_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_purpose_preference.xml, SPOTeam_android/app/src/main/res/layout/fragment_region_preference.xml, SPOTeam_android/app/src/main/res/layout/fragment_register_study.xml, SPOTeam_android/app/src/main/res/layout/fragment_theme_preference.xml
=> [fix] 마이페이지 ui 수정
